### ISSUE TITLE
Map functionality in Biocollect is not working properly

### ISSUE THREAD

**Issue by yasima-csiro** [AtlasOfLivingAustralia/ecodata-client-plugin#111]
Map functionality in Biocollect is not working properly with ecodata-client-plugin 3.1. It doesn't zoom to selected location. Following error is displayed in the console.

Check: https://biocollect-test.ala.org.au/acsa/bioActivity/create/d7aa7460-c2c6-454e-887f-73fddf5ad9d7

<img width="1785" alt="image" src="https://user-images.githubusercontent.com/72474143/127613733-a76dccfb-b7b6-478b-a02d-c60b5b60d753.png">

**Comment by chrisala** [comment]
This is a bug in BioCollect or a misconfigured form, not a bug in ecoata-client-plugin
