### ISSUE TITLE
Map is not displayed in Biocollect

### ISSUE THREAD

**Issue by yasima-csiro** [AtlasOfLivingAustralia/ecodata-client-plugin#112]
The Map is not displayed in the form : https://biocollect-test.ala.org.au/acsa/bioActivity/create/f86c3a76-e76a-42a6-9f91-0367b2ab5f6a

Following error is displayed in the console.

<img width="1789" alt="image" src="https://user-images.githubusercontent.com/72474143/127613995-797a5528-72e6-49c9-9f25-dc8867133918.png">

**Comment by chrisala** [comment]
This is a bug in BioCollect or a misconfigured form, not a bug in ecoata-client-plugin
